pub mod composition;
pub mod defaults;
pub mod determinism;
pub mod graph;
pub mod parsing;
pub mod scoring;
pub mod validation;
pub mod versioning;

// Re-export commonly used constants for easy access
pub use composition::{
    DEFAULT_MMR_LAMBDA, DEFAULT_TOKEN_BUDGET, DEFAULT_TOKEN_RESERVE, GREEDY_SELECTION_THRESHOLD,
    MAX_CANDIDATES_TO_SCORE,
};
pub use determinism::{
    DETERMINISM_CACHE_SIZE, FACET_SIMILARITY_WEIGHT, SIMILARITY_THRESHOLD,
    STRUCT_SIMILARITY_WEIGHT, TEXT_SIMILARITY_WEIGHT,
};
pub use scoring::{
    DEFAULT_AXES_MATCH_WEIGHT, DEFAULT_CONFIDENCE_THRESHOLD, DEFAULT_CONFIDENCE_WEIGHT,
    DEFAULT_FACET_COVERAGE_WEIGHT, DEFAULT_FRESHNESS_TAU_DAYS, DEFAULT_FRESHNESS_WEIGHT,
    DEFAULT_KEYWORD_WEIGHT, DEFAULT_TRUST_WEIGHT,
};
pub use versioning::{CONSTANTS_VERSION, RECIPE_VERSION, RULES_VERSION};
